# name: CI
# on:
#   push:
#     branches: [ "main" ]
# jobs:
#   build:
#     # The type of runner that the job will run on
#     runs-on: ["self-hosted", "macOS"]
#     steps:
#       - name: Run
#         run: echo AAAAAA
#         shell: bash


name: CI

on:
  push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Display operating system
      run: echo ${{ runner.os }}

    - name: Display date
      run: date
