name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ["macOS", "self-hosted"]
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
